// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-UB-UoBVzj3DD7zlRO_bj0VbatT9J8Uc',
    appId: '1:82598177424:web:1d53a88fde26c64a7fc615',
    messagingSenderId: '82598177424',
    projectId: 'flutter-flutterfire-ex01',
    authDomain: 'flutter-flutterfire-ex01.firebaseapp.com',
    storageBucket: 'flutter-flutterfire-ex01.firebasestorage.app',
    measurementId: 'G-EDCFZVZ3KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_ytsJoirNQkLMlB-_aJM4YYD2kPN-yB0',
    appId: '1:82598177424:android:65a38af4ce16079e7fc615',
    messagingSenderId: '82598177424',
    projectId: 'flutter-flutterfire-ex01',
    storageBucket: 'flutter-flutterfire-ex01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzLZwBfBtKlnKLmPTGJsU3-WFeDnYZqj0',
    appId: '1:82598177424:ios:cbcbd97ae22777cc7fc615',
    messagingSenderId: '82598177424',
    projectId: 'flutter-flutterfire-ex01',
    storageBucket: 'flutter-flutterfire-ex01.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirestoreEx04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzLZwBfBtKlnKLmPTGJsU3-WFeDnYZqj0',
    appId: '1:82598177424:ios:cbcbd97ae22777cc7fc615',
    messagingSenderId: '82598177424',
    projectId: 'flutter-flutterfire-ex01',
    storageBucket: 'flutter-flutterfire-ex01.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirestoreEx04',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-UB-UoBVzj3DD7zlRO_bj0VbatT9J8Uc',
    appId: '1:82598177424:web:f407711daafaf9c37fc615',
    messagingSenderId: '82598177424',
    projectId: 'flutter-flutterfire-ex01',
    authDomain: 'flutter-flutterfire-ex01.firebaseapp.com',
    storageBucket: 'flutter-flutterfire-ex01.firebasestorage.app',
    measurementId: 'G-EMGZ3RN4ES',
  );
}
