// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAok3tSnxs8T0nwp_Y6m_v1TxJ9B1_BhC8',
    appId: '1:801792147030:web:ef1de47cc7d48c012f05f7',
    messagingSenderId: '801792147030',
    projectId: 'flutter-flutterfire-ex04',
    authDomain: 'flutter-flutterfire-ex04.firebaseapp.com',
    storageBucket: 'flutter-flutterfire-ex04.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwoB9S88k3-8yqMAS9o8xnnQ6ZGYAVdfg',
    appId: '1:801792147030:android:5f7f5cbc1eebf0d52f05f7',
    messagingSenderId: '801792147030',
    projectId: 'flutter-flutterfire-ex04',
    storageBucket: 'flutter-flutterfire-ex04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSV84a7E--rzBKAvqrsS8uE7q5oRUSF9c',
    appId: '1:801792147030:ios:cca018989573818b2f05f7',
    messagingSenderId: '801792147030',
    projectId: 'flutter-flutterfire-ex04',
    storageBucket: 'flutter-flutterfire-ex04.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirestoreEx04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSV84a7E--rzBKAvqrsS8uE7q5oRUSF9c',
    appId: '1:801792147030:ios:cca018989573818b2f05f7',
    messagingSenderId: '801792147030',
    projectId: 'flutter-flutterfire-ex04',
    storageBucket: 'flutter-flutterfire-ex04.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirestoreEx04',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAok3tSnxs8T0nwp_Y6m_v1TxJ9B1_BhC8',
    appId: '1:801792147030:web:965b7627c58032a02f05f7',
    messagingSenderId: '801792147030',
    projectId: 'flutter-flutterfire-ex04',
    authDomain: 'flutter-flutterfire-ex04.firebaseapp.com',
    storageBucket: 'flutter-flutterfire-ex04.firebasestorage.app',
  );
}
